language: php
php:
 - 5.4
 - 5.5
 - 5.6
 - hhvm
before_install:
 - curl -s https://getcomposer.org/installer | php
 - php composer.phar install
script:
 - phpunit
matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm
